const userActionTypes = {
  LOG_IN_START: 'LOG_IN_START',
  LOG_IN_SUCCESS: 'LOG_IN_SUCCESS',
  LOG_IN_FAILURE: 'LOG_IN_FAILURE',
  LOG_OUT: 'LOG_OUT',

  GET_ORDER_START: 'GET_ORDER_START',
  GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS',
  GET_ORDER_FAILURE: 'GET_ORDER_FAILURE',

  GET_EVENTS_START: 'GET_EVENTS_START',
  GET_EVENTS_SUCCESS: 'GET_EVENTS_SUCCESS',
  GET_EVENTS_FAILURE: 'GET_EVENTS_FAILURE',

  CREATE_EVENT_START: 'CREATE_EVENT_START',
  CREATE_EVENT_SUCCESS: 'CREATE_EVENT_SUCCESS',
  CREATE_EVENT_FAILURE: 'CREATE_EVENT_FAILURE',

  UPDATE_EVENT_START: 'UPDATE_EVENT_START',
  UPDATE_EVENT_SUCCESS: 'UPDATE_EVENT_SUCCESS',
  UPDATE_EVENT_FAILURE: 'UPDATE_EVENT_FAILURE',

  DELETE_EVENT_START: 'DELETE_EVENT_START',
  DELETE_EVENT_SUCCESS: 'DELETE_EVENT_SUCCESS',
  DELETE_EVENT_FAILURE: 'DELETE_EVENT_FAILURE',

  GET_TEMPLATE_START: 'GET_TEMPLATE_START',
  GET_TEMPLATE_SUCCESS: 'GET_TEMPLATE_SUCCESS',
  GET_TEMPLATE_FAILURE: 'GET_TEMPLATE_FAILURE',

  CREATE_TEMPLATE_START: 'CREATE_TEMPLATE_START',
  CREATE_TEMPLATE_SUCCESS: 'CREATE_TEMPLATE_SUCCESS',
  CREATE_TEMPLATE_FAILURE: 'CREATE_TEMPLATE_FAILURE',

  UPDATE_TEMPLATE_START: 'UPDATE_TEMPLATE_START',
  UPDATE_TEMPLATE_SUCCESS: 'UPDATE_TEMPLATE_SUCCESS',
  UPDATE_TEMPLATE_FAILURE: 'UPDATE_TEMPLATE_FAILURE',

  DELETE_TEMPLATE_START:"DELETE_TEMPLATE_START",
  DELETE_TEMPLATE_SUCCESS:"DELETE_TEMPLATE_SUCCESS",
  DELETE_TEMPLATE_FAILURE:"DELETE_TEMPLATE_FAILURE",

  GET_RULES_START:"GET_RULES_START",
  GET_RULES_SUCCESS:"GET_RULES_SUCCESS",
  GET_RULES_FAILURE:"GET_RULES_FAILURE",

  GET_LOOKUP_START:"GET_LOOKUP_START",
  GET_LOOKUP_SUCCESS:"GET_LOOKUP_SUCCESS",
  GET_LOOKUP_FAILURE:"GET_LOOKUP_FAILURE",

  CREATE_RULE_START:"CREATE_RULE_STATR",
  CREATE_RULE_SUCCESS:"CREATE_RULE_SUCCESS",
  CREATE_RULE_FAILURE:"CREATE_RULE_FAILURE",

  UPDATE_RULE_START:"UPDATE_RULE_START",
  UPDATE_RULE_SUCCESS:"UPDATE_RULE_SUCCESS",
  UPDATE_RULE_FAILURE:"UPDATE_RULE_FAILURE",

  GET_CUSTOMER_START:"GET_CUSTOMER_START",
  GET_CUSTOMER_SUCCESS:"GET_CUSTOMER_SUCCESS",
  GET_CUSTOMER_FAILURE:"GET_CUSTOMER_FAILURE",

  CREATE_CUSTOMER_START:"CREATE_CUSTOMER_START",
  CREATE_CUSTOMER_SUCCESS:"CREATE_CUSTOMER_SUCCESS",
  CREATE_CUSTOMER_FAILURE:"CREATE_CUSTOMER_FAILURE",

  UPDATE_CUSTOMER_START:"UPDATE_CUSTOMER_START",
  UPDATE_CUSTOMER_SUCCESS:"UPDATE_CUSTOMER_SUCCESS",
  UPDATE_CUSTOMER_FAILURE:"UPDATE_CUSTOMER_FAILURE",

  GET_STORAGE_START:"GET_STORAGE_START",
  GET_STORAGE_SUCCESS:"GET_STORAGE_SUCCESS",
  GET_STORAGE_FAILURE:"GET_STORAGE_FAILURE",

  GET_POOL_PROVIDER_START:'GET_POOL_PROVIDER_START',
  GET_POOL_PROVIDER_SUCCESS:'GET_POOL_PROVIDER_SUCCESS',
  GET_POOL_PROVIDER_FAILURE:'GET_POOL_PROVIDER_FAILURE',
};

export default userActionTypes;

